In [1]:
import numpy as np
x=np.array([
    [0,0,0],
    [0,1,0],
    [1,0,0],
    [1,1,0],
    [0,1,1],
    [1,1,1],
    [1,0,1],
    [0,0,1],
])
y=np.array([0,1,0,1,0,1,0,0])

In [2]:
w1 = np.array([0,1,-1])
b1=-0.5
w2 = np.array([1,1,0])
b2=-1.5
w3 = np.array([0,-1,1])
b3=-0.5

In [3]:
# h1=[w1[0]*x[i][0]+w2[1]*x[i][1]+w3[2]*x[i][2] for i in range(len(x))]
h1=np.dot(x,w1)+b1
# h1=[w1[0]*x[i][0]+w2[1]*x[i][1]+w3[2]*x[i][2] for i in range(len(x))]
# h1=[w1[0]*x[i][0]+w2[1]*x[i][1]+w3[2]*x[i][2] for i in range(len(x))]
h2=np.dot(x,w2)+b2
h3=np.dot(x,w3)+b3

In [4]:
h1,h2,h3

(array([-0.5,  0.5, -0.5,  0.5, -0.5, -0.5, -1.5, -1.5]),
 array([-1.5, -0.5, -0.5,  0.5, -0.5,  0.5, -0.5, -1.5]),
 array([-0.5, -1.5, -0.5, -1.5, -0.5, -0.5,  0.5,  0.5]))

In [5]:
def act_func(z):
    return 1 if z>=0 else 0

In [6]:
y1=[act_func(z) for z in h1]
y2=[act_func(z) for z in h2]
y3=[act_func(z) for z in h3]

In [7]:
y1,y2,y3

([0, 1, 0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1, 1])

In [8]:
w4 = [1,1,-2]
b4=-0.5
y_weight=[y1[i]*w4[0]+y2[i]*w4[1]+y3[i]*w4[2]+b4 for i in range(len(y))]
y_pred=[act_func(z) for z in y_weight]
loss=y-y_pred
print(loss)

[0 0 0 0 0 0 0 0]


In [9]:
print(y_weight)
print(y_pred)
print(y)

[-0.5, 0.5, -0.5, 1.5, -0.5, 0.5, -2.5, -2.5]
[0, 1, 0, 1, 0, 1, 0, 0]
[0 1 0 1 0 1 0 0]


In [10]:
x=np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
y=np.array([0,1,0,1])

In [ ]:
w=np.random.randn(x.shape[1])
w

In [13]:
b=np.random.randn()
b

-0.8538382595798