<a href="https://colab.research.google.com/github/Khushibung05/LSTM/blob/main/lstm2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# ============================================
# TASK 1
# TEXT PREPROCESSING
# TOKENIZATION
# SEQUENCE GENERATION
# PADDING
# ============================================

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

# ============================================
# DATASET
# ============================================

sentences = [
    "I love deep learning",
    "I love artificial intelligence",
    "Deep learning is powerful",
    "Artificial intelligence is transforming the world",
    "I enjoy learning neural networks",
    "Neural networks are inspired by the human brain"
]

# ============================================
# TOKENIZATION
# ============================================

tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index

print("WORD INDEX:\n")

print(word_index)

# ============================================
# SEQUENCE GENERATION
# ============================================

sequences = tokenizer.texts_to_sequences(
    sentences
)

print("\nSEQUENCES:\n")

for seq in sequences:
    print(seq)

# ============================================
# PADDING
# ============================================

padded_sequences = pad_sequences(
    sequences,
    padding='pre'
)

print("\nPADDED SEQUENCES:\n")

print(padded_sequences)

WORD INDEX:

{'i': 1, 'learning': 2, 'love': 3, 'deep': 4, 'artificial': 5, 'intelligence': 6, 'is': 7, 'the': 8, 'neural': 9, 'networks': 10, 'powerful': 11, 'transforming': 12, 'world': 13, 'enjoy': 14, 'are': 15, 'inspired': 16, 'by': 17, 'human': 18, 'brain': 19}

SEQUENCES:

[1, 3, 4, 2]
[1, 3, 5, 6]
[4, 2, 7, 11]
[5, 6, 7, 12, 8, 13]
[1, 14, 2, 9, 10]
[9, 10, 15, 16, 17, 8, 18, 19]

PADDED SEQUENCES:

[[ 0  0  0  0  1  3  4  2]
 [ 0  0  0  0  1  3  5  6]
 [ 0  0  0  0  4  2  7 11]
 [ 0  0  5  6  7 12  8 13]
 [ 0  0  0  1 14  2  9 10]
 [ 9 10 15 16 17  8 18 19]]


In [3]:
# ============================================
# TASK 2
# CREATE INPUT-OUTPUT SEQUENCES
# FOR NEXT WORD PREDICTION
# ============================================

input_sequences = []

# Generate sequences

for sentence in sentences:

    token_list = tokenizer.texts_to_sequences(
        [sentence]
    )[0]

    # Create n-gram sequences

    for i in range(1, len(token_list)):

        n_gram_sequence = token_list[:i+1]

        input_sequences.append(
            n_gram_sequence
        )

# ============================================
# DISPLAY SEQUENCES
# ============================================

print("INPUT SEQUENCES:\n")

for seq in input_sequences:
    print(seq)

# ============================================
# PAD INPUT SEQUENCES
# ============================================

max_sequence_len = max(
    [len(seq) for seq in input_sequences]
)

input_sequences = np.array(
    pad_sequences(
        input_sequences,
        maxlen=max_sequence_len,
        padding='pre'
    )
)

# ============================================
# CREATE X AND y
# ============================================

X = input_sequences[:, :-1]

y = input_sequences[:, -1]

print("\nX SHAPE:", X.shape)

print("y SHAPE:", y.shape)

# ============================================
# VOCAB SIZE
# ============================================

total_words = len(word_index) + 1

# ============================================
# ONE HOT ENCODING
# ============================================

from tensorflow.keras.utils import to_categorical

y = to_categorical(
    y,
    num_classes=total_words
)

print("\nONE HOT y SHAPE:", y.shape)

INPUT SEQUENCES:

[1, 3]
[1, 3, 4]
[1, 3, 4, 2]
[1, 3]
[1, 3, 5]
[1, 3, 5, 6]
[4, 2]
[4, 2, 7]
[4, 2, 7, 11]
[5, 6]
[5, 6, 7]
[5, 6, 7, 12]
[5, 6, 7, 12, 8]
[5, 6, 7, 12, 8, 13]
[1, 14]
[1, 14, 2]
[1, 14, 2, 9]
[1, 14, 2, 9, 10]
[9, 10]
[9, 10, 15]
[9, 10, 15, 16]
[9, 10, 15, 16, 17]
[9, 10, 15, 16, 17, 8]
[9, 10, 15, 16, 17, 8, 18]
[9, 10, 15, 16, 17, 8, 18, 19]

X SHAPE: (25, 7)
y SHAPE: (25,)

ONE HOT y SHAPE: (25, 20)


In [4]:
# ============================================
# TASK 3
# SIMPLE RNN MODEL
# ============================================

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.layers import Dense

# ============================================
# BUILD MODEL
# ============================================

rnn_model = Sequential()

# Embedding Layer

rnn_model.add(
    Embedding(
        input_dim=total_words,
        output_dim=10,
        input_length=max_sequence_len-1
    )
)

# SimpleRNN Layer

rnn_model.add(
    SimpleRNN(
        units=100
    )
)

# Output Layer

rnn_model.add(
    Dense(
        total_words,
        activation='softmax'
    )
)

# ============================================
# COMPILE MODEL
# ============================================

rnn_model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# ============================================
# MODEL SUMMARY
# ============================================

rnn_model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
# ============================================
# TASK 4
# TRAIN SIMPLE RNN MODEL
# ============================================

rnn_model.fit(
    X,
    y,
    epochs=300,
    verbose=1
)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0400 - loss: 2.9997
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.2000 - loss: 2.9826
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.2000 - loss: 2.9652
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.1600 - loss: 2.9466
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.1600 - loss: 2.9259
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.1600 - loss: 2.9022
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.1600 - loss: 2.8753
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.1200 - loss: 2.8452
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.1200 - loss: 2.8142
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.1200 - loss: 2.7873
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.1200 - loss: 2.7713
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.1200 - lo

In [6]:
# ============================================
# TEST RNN PREDICTION
# ============================================

input_text = "i love"

# Convert text to sequence

token_list = tokenizer.texts_to_sequences(
    [input_text]
)[0]

# Padding

token_list = pad_sequences(
    [token_list],
    maxlen=max_sequence_len-1,
    padding='pre'
)

# Predict next word

predicted = np.argmax(
    rnn_model.predict(token_list),
    axis=-1
)

# Convert number to word

for word, index in word_index.items():

    if index == predicted:
        predicted_word = word

print("\nNEXT WORD PREDICTION:")
print(input_text, "->", predicted_word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 582ms/step

NEXT WORD PREDICTION:
i love -> deep


In [7]:
# ============================================
# TASK 5
# LSTM MODEL
# ============================================

from tensorflow.keras.layers import LSTM

# ============================================
# BUILD LSTM MODEL
# ============================================

lstm_model = Sequential()

# Embedding Layer

lstm_model.add(
    Embedding(
        input_dim=total_words,
        output_dim=10,
        input_length=max_sequence_len-1
    )
)

# LSTM Layer

lstm_model.add(
    LSTM(
        units=100
    )
)

# Output Layer

lstm_model.add(
    Dense(
        total_words,
        activation='softmax'
    )
)

# ============================================
# COMPILE MODEL
# ============================================

lstm_model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# ============================================
# MODEL SUMMARY
# ============================================

lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
# ============================================
# TASK 6
# TRAIN LSTM MODEL
# ============================================

lstm_model.fit(
    X,
    y,
    epochs=300,
    verbose=1
)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.0000e+00 - loss: 2.9958
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.0400 - loss: 2.9933
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.1200 - loss: 2.9906
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.2000 - loss: 2.9879
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.1600 - loss: 2.9849
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.1600 - loss: 2.9817
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.1200 - loss: 2.9781
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.1200 - loss: 2.9741
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.1200 - loss: 2.9697
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.1200 - loss: 2.9646
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.1200 - loss: 2.9589
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.1200 - 

In [9]:
# ============================================
# TEST LSTM PREDICTION
# ============================================

input_text = "i love"

# Convert to sequence

token_list = tokenizer.texts_to_sequences(
    [input_text]
)[0]

# Padding

token_list = pad_sequences(
    [token_list],
    maxlen=max_sequence_len-1,
    padding='pre'
)

# Predict next word

predicted = np.argmax(
    lstm_model.predict(token_list),
    axis=-1
)

# Convert index to word

for word, index in word_index.items():

    if index == predicted:
        predicted_word = word

print("\nNEXT WORD PREDICTION:")
print(input_text, "->", predicted_word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 480ms/step

NEXT WORD PREDICTION:
i love -> deep


In [10]:
# ============================================
# TASK 7
# COMPARE RNN AND LSTM
# ============================================

# ============================================
# RNN EVALUATION
# ============================================

rnn_loss, rnn_accuracy = rnn_model.evaluate(
    X,
    y,
    verbose=0
)

print("\n================================")
print("SIMPLE RNN PERFORMANCE")
print("================================")

print("RNN Accuracy:", rnn_accuracy)
print("RNN Loss:", rnn_loss)

# ============================================
# LSTM EVALUATION
# ============================================

lstm_loss, lstm_accuracy = lstm_model.evaluate(
    X,
    y,
    verbose=0
)

print("\n================================")
print("LSTM PERFORMANCE")
print("================================")

print("LSTM Accuracy:", lstm_accuracy)
print("LSTM Loss:", lstm_loss)

# ============================================
# NEXT WORD PREDICTION COMPARISON
# ============================================

input_text = "i love"

print("\n================================")
print("NEXT WORD PREDICTION COMPARISON")
print("================================")

# ============================================
# PREPARE INPUT
# ============================================

token_list = tokenizer.texts_to_sequences(
    [input_text]
)[0]

token_list = pad_sequences(
    [token_list],
    maxlen=max_sequence_len-1,
    padding='pre'
)

# ============================================
# RNN PREDICTION
# ============================================

rnn_predicted = np.argmax(
    rnn_model.predict(token_list),
    axis=-1
)

rnn_word = ""

for word, index in word_index.items():

    if index == rnn_predicted:

        rnn_word = word

# ============================================
# LSTM PREDICTION
# ============================================

lstm_predicted = np.argmax(
    lstm_model.predict(token_list),
    axis=-1
)

lstm_word = ""

for word, index in word_index.items():

    if index == lstm_predicted:

        lstm_word = word

# ============================================
# DISPLAY RESULTS
# ============================================

print("\nInput Text:", input_text)

print("\nSimpleRNN Prediction:")
print(input_text, "->", rnn_word)

print("\nLSTM Prediction:")
print(input_text, "->", lstm_word)

# ============================================
# FINAL COMPARISON
# ============================================

print("\n================================")
print("MODEL COMPARISON")
print("================================")

if lstm_accuracy > rnn_accuracy:

    print("""
LSTM performed better because:

- Better memory handling
- Smart gates
- Better context understanding
- Improved sequence learning
""")

else:

    print("""
SimpleRNN performed similarly
because dataset is very small.
""")


SIMPLE RNN PERFORMANCE
RNN Accuracy: 0.9200000166893005
RNN Loss: 0.1427053064107895

LSTM PERFORMANCE
LSTM Accuracy: 0.9200000166893005
LSTM Loss: 0.19868674874305725

NEXT WORD PREDICTION COMPARISON
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step

Input Text: i love

SimpleRNN Prediction:
i love -> deep

LSTM Prediction:
i love -> deep

MODEL COMPARISON

SimpleRNN performed similarly
because dataset is very small.

