In [9]:
import numpy as np
np.random.seed(0)
x=np.array([
    [120,85,150,95],# Glucose
    [25,30,35,22] # BMI
])
#Normalize i/p's
x=x/200
y=np.array([1,0,1,0]) # Risk of Diabetes
print(x.shape)
print(y.shape)

(2, 4)
(4,)


In [5]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [3]:
# Hidden Layer (3 Neurons,2 Inputs)
w1=np.random.randn(3,2)*0.1
b1=np.zeros((3,1))
# O/P Layer (1 Neuron,3 Hidden Inputs)
w2=np.random.randn(1,3)*0.1
b2=np.zeros((1,1))

In [14]:
w1,b1

(array([[0.04105985, 0.01440436],
        [0.14542735, 0.07610377],
        [0.0121675 , 0.04438632]]),
 array([[0.],
        [0.],
        [0.]]))

In [7]:
z1=np.dot(w1,x)+b1
a1=sigmoid(z1)
z2=np.dot(w2,a1)+b2
a2=sigmoid(z2)
print("Predicted Output:",a2)

Predicted Output: [[0.52121128 0.52097929 0.5214585  0.5210232 ]]


In [26]:
a1.T

array([[6.18210727e-02, 6.18207835e-02, 1.95211096e-20],
       [2.17166541e-18, 1.43117581e-32, 1.39448682e-14],
       [1.00000000e+00, 1.00000000e+00, 1.94672694e-25],
       [2.55985391e-13, 3.35180202e-23, 2.91277825e-16]])

In [12]:
m=y.shape[0]
loss=-np.sum(y*np.log(a2+1e-8)+(1-y)*np.log(1-a2+1e-8))/m
loss

np.float64(0.693709963258477)

In [22]:
dz2=a2-y
dw2=(1/m)*np.dot(dz2,a1.T)
db2=(1/m)*np.sum(dz2,axis=1,keepdims=True)

In [23]:
da1=np.dot(w2.T,dz2)
dz1=da1*(1-a1)
dw1=(1/m)*np.dot(dz1,x.T)
db1=(1/m)*np.sum(dz1,axis=1,keepdims=True)

In [24]:
learning_rate=1
w2-=learning_rate*dw2
b2-=learning_rate*db2

w1-=learning_rate*dw1
b1-=learning_rate*db1

In [25]:
epoch=5000
for i in range(epoch):
    z1=np.dot(w1,x)+b1
    a1=sigmoid(z1)

    z2=np.dot(w2,a1)+b2
    a2=sigmoid(z2)

    loss=-np.sum(y*np.log(a2+1e-8)+(1-y)*np.log(1-a2+1e-8))/m

    dz2=a2-y
    dw2=(1/m)*np.dot(dz2,a1.T)
    db2=(1/m)*np.sum(dz2,axis=1,keepdims=True)

    da1=np.dot(w2.T,dz2)
    dz1=da1*(1-a1)

    dw1=(1/m)*np.dot(dz1,x.T)
    db1=(1/m)*np.sum(dz1,axis=1,keepdims=True)

    w2-=0.5*dw2
    b2-=0.5*db2
    w1-=0.5*dw1
    b1-=0.5*db1

    if i%100==0:
        print(f"epoch: {i} loss: {loss}")

epoch: 0 loss: 0.6928870353136822
epoch: 100 loss: 0.691622958115055
epoch: 200 loss: 0.6855799396452711
epoch: 300 loss: 0.6573510730582998
epoch: 400 loss: 0.6108440423603594
epoch: 500 loss: 0.5903344527783941
epoch: 600 loss: 0.5750863954892558
epoch: 700 loss: 0.5574515924017619
epoch: 800 loss: 0.5368143398582692
epoch: 900 loss: 0.5095181439779212
epoch: 1000 loss: 0.4648851197352946
epoch: 1100 loss: 0.4103857894277282
epoch: 1200 loss: 0.3692610628362786
epoch: 1300 loss: 0.35233695227058714
epoch: 1400 loss: 0.3430505702127714
epoch: 1500 loss: 0.3372335242850988
epoch: 1600 loss: 0.33272832815690395
epoch: 1700 loss: 0.3284571007718532
epoch: 1800 loss: 0.32401200544807923
epoch: 1900 loss: 0.31931040246468473
epoch: 2000 loss: 0.314392778277238
epoch: 2100 loss: 0.3093313531164849
epoch: 2200 loss: 0.30419618346871014
epoch: 2300 loss: 0.29904519133923013
epoch: 2400 loss: 0.2939228705306746
epoch: 2500 loss: 0.2888617664163513
epoch: 2600 loss: 0.28388463842854467
epoch: 2